"""phase 2 inventory schema

Revision ID: 48a3c620953c
Revises: f9d471469add
Create Date: 2026-08-21 14:32:17.015528
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "48a3c620953c"
down_revision: str | None = "f9d471469add"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_credential",
        sa.Column(
            "auth_type",
            sa.Enum("API_KEY", "OAUTH_CLIENT_CREDENTIALS", "BASIC", name="credentialauthtype_enum"),
            nullable=False,
        ),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("last_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_credential")),
    )
    op.create_index(
        op.f("ix_integration_credential_created_at"),
        "integration_credential",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "vendor_alias",
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("canonical_vendor", sa.String(length=200), nullable=False),
        sa.Column("canonical_product", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_alias")),
        sa.UniqueConstraint("alias", name=op.f("uq_vendor_alias_alias")),
    )
    op.create_index(
        op.f("ix_vendor_alias_canonical_vendor"), "vendor_alias", ["canonical_vendor"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_alias_created_at"), "vendor_alias", ["created_at"], unique=False
    )
    op.create_table(
        "inventory_source",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "CSV_DESKTOP_CENTRAL",
                "CSV_LANSWEEPER",
                "CSV_AZURE",
                "API_DESKTOP_CENTRAL",
                "API_AZURE_ARM",
                "API_MS_GRAPH",
                name="inventorysourcekind_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "mode", sa.Enum("AGGREGATE", "DETAILED", name="inventorymode_enum"), nullable=False
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("schedule_cron", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_sync_status",
            sa.Enum("NEVER", "OK", "PARTIAL", "ERROR", name="syncstatus_enum"),
            nullable=False,
        ),
        sa.Column("last_sync_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["integration_credential.id"],
            name=op.f("fk_inventory_source_credential_id_integration_credential"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_source")),
        sa.UniqueConstraint("name", name=op.f("uq_inventory_source_name")),
    )
    op.create_index(
        op.f("ix_inventory_source_created_at"), "inventory_source", ["created_at"], unique=False
    )
    op.create_table(
        "inventory_snapshot",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "mode", sa.Enum("AGGREGATE", "DETAILED", name="inventorymode_enum"), nullable=False
        ),
        sa.Column("device_count", sa.Integer(), nullable=True),
        sa.Column("software_row_count", sa.Integer(), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("raw_file_blob_id", sa.UUID(), nullable=True),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_file_blob_id"],
            ["blob.id"],
            name=op.f("fk_inventory_snapshot_raw_file_blob_id_blob"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["inventory_source.id"],
            name=op.f("fk_inventory_snapshot_source_id_inventory_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["user_account.id"],
            name=op.f("fk_inventory_snapshot_uploaded_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_snapshot")),
    )
    op.create_index(
        op.f("ix_inventory_snapshot_created_at"), "inventory_snapshot", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_snapshot_source_id"), "inventory_snapshot", ["source_id"], unique=False
    )
    op.create_index(
        "uq_inventory_snapshot_latest_per_source",
        "inventory_snapshot",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("is_latest"),
    )
    op.create_table(
        "scan_run",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("initiated_by_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETE", "FAILED", name="scanstatus_enum"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("affected_device_count", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_scan_run_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_id"],
            ["user_account.id"],
            name=op.f("fk_scan_run_initiated_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_run")),
    )
    op.create_index(op.f("ix_scan_run_advisory_id"), "scan_run", ["advisory_id"], unique=False)
    op.create_index(op.f("ix_scan_run_created_at"), "scan_run", ["created_at"], unique=False)
    op.create_table(
        "inventory_device",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("device_identifier", sa.Text(), nullable=False),
        sa.Column("hostname", sa.Text(), nullable=True),
        sa.Column("os_name", sa.Text(), nullable=True),
        sa.Column("os_version", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["inventory_snapshot.id"],
            name=op.f("fk_inventory_device_snapshot_id_inventory_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_device")),
    )
    op.create_index(
        op.f("ix_inventory_device_created_at"), "inventory_device", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_device_snapshot_id"), "inventory_device", ["snapshot_id"], unique=False
    )
    op.create_table(
        "inventory_software",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("vendor_raw", sa.Text(), nullable=True),
        sa.Column("product_raw", sa.Text(), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("version_raw", sa.Text(), nullable=True),
        sa.Column("version_normalized", sa.Text(), nullable=True),
        sa.Column("version_parts", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("SOFTWARE", "OPERATING_SYSTEM", name="inventoryitemkind_enum"),
            nullable=False,
        ),
        sa.Column("device_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["inventory_snapshot.id"],
            name=op.f("fk_inventory_software_snapshot_id_inventory_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_software")),
    )
    op.create_index(
        op.f("ix_inventory_software_created_at"), "inventory_software", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_software_product"), "inventory_software", ["product"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_software_snapshot_id"),
        "inventory_software",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_software_snapshot_vendor_product",
        "inventory_software",
        ["snapshot_id", "vendor", "product"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_software_vendor"), "inventory_software", ["vendor"], unique=False
    )
    op.create_table(
        "scan_match",
        sa.Column("scan_run_id", sa.UUID(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=True),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("matched_version", sa.Text(), nullable=False),
        sa.Column("affected_range", sa.Text(), nullable=False),
        sa.Column("device_count", sa.Integer(), nullable=False),
        sa.Column("device_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "match_method",
            sa.Enum("CPE_RANGE", "CPE_EXACT", "TEXT_RANGE", "FUZZY_NAME", name="matchmethod_enum"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("CONFIRMED", "LIKELY", "POSSIBLE", name="matchconfidence_enum"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_run.id"],
            name=op.f("fk_scan_match_scan_run_id_scan_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["inventory_snapshot.id"],
            name=op.f("fk_scan_match_snapshot_id_inventory_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_match")),
    )
    op.create_index(op.f("ix_scan_match_confidence"), "scan_match", ["confidence"], unique=False)
    op.create_index(op.f("ix_scan_match_created_at"), "scan_match", ["created_at"], unique=False)
    op.create_index(op.f("ix_scan_match_cve_id"), "scan_match", ["cve_id"], unique=False)
    op.create_index(op.f("ix_scan_match_scan_run_id"), "scan_match", ["scan_run_id"], unique=False)
    op.create_table(
        "inventory_device_software",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("version_normalized", sa.Text(), nullable=True),
        sa.Column("version_parts", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["inventory_device.id"],
            name=op.f("fk_inventory_device_software_device_id_inventory_device"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_device_software")),
    )
    op.create_index(
        op.f("ix_inventory_device_software_created_at"),
        "inventory_device_software",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_device_software_device_id"),
        "inventory_device_software",
        ["device_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inventory_device_software_device_id"), table_name="inventory_device_software"
    )
    op.drop_index(
        op.f("ix_inventory_device_software_created_at"), table_name="inventory_device_software"
    )
    op.drop_table("inventory_device_software")
    op.drop_index(op.f("ix_scan_match_scan_run_id"), table_name="scan_match")
    op.drop_index(op.f("ix_scan_match_cve_id"), table_name="scan_match")
    op.drop_index(op.f("ix_scan_match_created_at"), table_name="scan_match")
    op.drop_index(op.f("ix_scan_match_confidence"), table_name="scan_match")
    op.drop_table("scan_match")
    op.drop_index(op.f("ix_inventory_software_vendor"), table_name="inventory_software")
    op.drop_index("ix_inventory_software_snapshot_vendor_product", table_name="inventory_software")
    op.drop_index(op.f("ix_inventory_software_snapshot_id"), table_name="inventory_software")
    op.drop_index(op.f("ix_inventory_software_product"), table_name="inventory_software")
    op.drop_index(op.f("ix_inventory_software_created_at"), table_name="inventory_software")
    op.drop_table("inventory_software")
    op.drop_index(op.f("ix_inventory_device_snapshot_id"), table_name="inventory_device")
    op.drop_index(op.f("ix_inventory_device_created_at"), table_name="inventory_device")
    op.drop_table("inventory_device")
    op.drop_index(op.f("ix_scan_run_created_at"), table_name="scan_run")
    op.drop_index(op.f("ix_scan_run_advisory_id"), table_name="scan_run")
    op.drop_table("scan_run")
    op.drop_index(
        "uq_inventory_snapshot_latest_per_source",
        table_name="inventory_snapshot",
        postgresql_where=sa.text("is_latest"),
    )
    op.drop_index(op.f("ix_inventory_snapshot_source_id"), table_name="inventory_snapshot")
    op.drop_index(op.f("ix_inventory_snapshot_created_at"), table_name="inventory_snapshot")
    op.drop_table("inventory_snapshot")
    op.drop_index(op.f("ix_inventory_source_created_at"), table_name="inventory_source")
    op.drop_table("inventory_source")
    op.drop_index(op.f("ix_vendor_alias_created_at"), table_name="vendor_alias")
    op.drop_index(op.f("ix_vendor_alias_canonical_vendor"), table_name="vendor_alias")
    op.drop_table("vendor_alias")
    op.drop_index(op.f("ix_integration_credential_created_at"), table_name="integration_credential")
    op.drop_table("integration_credential")
    # ### end Alembic commands ###

    # ─── native enum types ───────────────────────────────────────────────────
    # See 4f03b42cc69d's downgrade() for why this loop exists: op.drop_table()
    # does not drop the PostgreSQL ENUM types the dropped columns used.
    for enum_name in (
        "credentialauthtype_enum",
        "inventorysourcekind_enum",
        "inventorymode_enum",
        "syncstatus_enum",
        "inventoryitemkind_enum",
        "scanstatus_enum",
        "matchmethod_enum",
        "matchconfidence_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name};")
