"""initial schema

Revision ID: 4f03b42cc69d
Revises:
Create Date: 2026-08-20 15:03:36.697022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4f03b42cc69d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blob",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blob")),
    )
    op.create_index(op.f("ix_blob_created_at"), "blob", ["created_at"], unique=False)
    op.create_index(op.f("ix_blob_sha256"), "blob", ["sha256"], unique=True)
    op.create_table(
        "cve_cpe",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("cpe_uri", sa.Text(), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=False),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("version_start", sa.String(length=100), nullable=True),
        sa.Column("version_start_inclusive", sa.Boolean(), nullable=False),
        sa.Column("version_end", sa.String(length=100), nullable=True),
        sa.Column("version_end_inclusive", sa.Boolean(), nullable=False),
        sa.Column("vulnerable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_cpe")),
        sa.UniqueConstraint(
            "cve_id",
            "cpe_uri",
            "version_start",
            "version_end",
            name=op.f("uq_cve_cpe_cve_id_cpe_uri_version_start_version_end"),
        ),
    )
    op.create_index(op.f("ix_cve_cpe_created_at"), "cve_cpe", ["created_at"], unique=False)
    op.create_index(op.f("ix_cve_cpe_cve_id"), "cve_cpe", ["cve_id"], unique=False)
    op.create_index(op.f("ix_cve_cpe_product"), "cve_cpe", ["product"], unique=False)
    op.create_index(op.f("ix_cve_cpe_vendor"), "cve_cpe", ["vendor"], unique=False)
    op.create_index("ix_cve_cpe_vendor_product", "cve_cpe", ["vendor", "product"], unique=False)
    op.create_table(
        "source",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_code", sa.String(length=20), nullable=False),
        sa.Column("sender_patterns", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "default_type_hint",
            sa.Enum(
                "CVE_ADVISORY",
                "SECURITY_BULLETIN",
                "THREAT_LANDSCAPE",
                "OTHER",
                name="advisorytype_enum",
            ),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("name", name=op.f("uq_source_name")),
        sa.UniqueConstraint("short_code", name=op.f("uq_source_short_code")),
    )
    op.create_index(op.f("ix_source_created_at"), "source", ["created_at"], unique=False)
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.Enum("VIEWER", "ANALYST", "ADMIN", name="role_enum"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_user_account_external_subject")),
    )
    op.create_index(
        op.f("ix_user_account_created_at"), "user_account", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_account_email"), "user_account", ["email"], unique=True)
    op.create_table(
        "advisory",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "CVE_ADVISORY",
                "SECURITY_BULLETIN",
                "THREAT_LANDSCAPE",
                "OTHER",
                name="advisorytype_enum",
            ),
            nullable=False,
        ),
        sa.Column("type_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("source_type_raw", sa.String(length=64), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity_enum"),
            nullable=True,
        ),
        sa.Column("cvss_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ACKNOWLEDGED",
                "TRIAGED",
                "IN_PROGRESS",
                "AWAITING_VENDOR",
                "REMEDIATED",
                "RISK_ACCEPTED",
                "NOT_APPLICABLE",
                "CLOSED",
                name="advisorystatus_enum",
            ),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.Enum("P1", "P2", "P3", "P4", name="priority_enum"), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "ack_channel", sa.Enum("EMAIL", "PHONE", "OTHER", name="ackchannel_enum"), nullable=True
        ),
        sa.Column("ack_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detected_on", sa.Date(), nullable=True),
        sa.Column("upstream_reference", sa.String(length=200), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("title_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("raw_email_blob_id", sa.UUID(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by_id"],
            ["user_account.id"],
            name=op.f("fk_advisory_acknowledged_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user_account.id"],
            name=op.f("fk_advisory_assignee_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_email_blob_id"],
            ["blob.id"],
            name=op.f("fk_advisory_raw_email_blob_id_blob"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_advisory_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory")),
    )
    op.create_index(op.f("ix_advisory_ack_due_at"), "advisory", ["ack_due_at"], unique=False)
    op.create_index(
        op.f("ix_advisory_acknowledged_at"), "advisory", ["acknowledged_at"], unique=False
    )
    op.create_index(op.f("ix_advisory_created_at"), "advisory", ["created_at"], unique=False)
    op.create_index(op.f("ix_advisory_dedupe_hash"), "advisory", ["dedupe_hash"], unique=True)
    op.create_index(op.f("ix_advisory_external_ref"), "advisory", ["external_ref"], unique=False)
    op.create_index(op.f("ix_advisory_message_id"), "advisory", ["message_id"], unique=False)
    op.create_index(op.f("ix_advisory_priority"), "advisory", ["priority"], unique=False)
    op.create_index(op.f("ix_advisory_received_at"), "advisory", ["received_at"], unique=False)
    op.create_index(
        op.f("ix_advisory_resolution_due_at"), "advisory", ["resolution_due_at"], unique=False
    )
    op.create_index(
        "ix_advisory_search_vector",
        "advisory",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_advisory_severity"), "advisory", ["severity"], unique=False)
    op.create_index(op.f("ix_advisory_source_id"), "advisory", ["source_id"], unique=False)
    op.create_index(
        "ix_advisory_source_received", "advisory", ["source_id", "received_at"], unique=False
    )
    op.create_index(op.f("ix_advisory_status"), "advisory", ["status"], unique=False)
    op.create_index("ix_advisory_status_severity", "advisory", ["status", "severity"], unique=False)
    op.create_index(
        op.f("ix_advisory_title_fingerprint"), "advisory", ["title_fingerprint"], unique=False
    )
    op.create_table(
        "api_token",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_prefix", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user_account.id"],
            name=op.f("fk_api_token_created_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_token")),
    )
    op.create_index(op.f("ix_api_token_created_at"), "api_token", ["created_at"], unique=False)
    op.create_index(op.f("ix_api_token_token_prefix"), "api_token", ["token_prefix"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_label", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user_account.id"],
            name=op.f("fk_audit_log_actor_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_session_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
    )
    op.create_index(
        op.f("ix_user_session_created_at"), "user_session", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_session_expires_at"), "user_session", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    op.create_table(
        "advisory_attachment",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("blob_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extracted_text_blob_id", sa.UUID(), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum("TEXT_LAYER", "OCR", "FAILED", name="extractionmethod_enum"),
            nullable=True,
        ),
        sa.Column("extraction_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_attachment_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blob.id"],
            name=op.f("fk_advisory_attachment_blob_id_blob"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["extracted_text_blob_id"],
            ["blob.id"],
            name=op.f("fk_advisory_attachment_extracted_text_blob_id_blob"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_attachment")),
    )
    op.create_index(
        op.f("ix_advisory_attachment_advisory_id"),
        "advisory_attachment",
        ["advisory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_attachment_created_at"),
        "advisory_attachment",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "advisory_cve",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("found_in", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("cvss_v3_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("cvss_v3_vector", sa.String(length=120), nullable=True),
        sa.Column("cvss_v4_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("cvss_v4_vector", sa.String(length=160), nullable=True),
        sa.Column("nvd_description", sa.Text(), nullable=True),
        sa.Column("nvd_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "enrichment_status",
            sa.Enum(
                "PENDING",
                "OK",
                "NOT_FOUND",
                "ERROR",
                "SKIPPED_OFFLINE",
                name="enrichmentstatus_enum",
            ),
            nullable=False,
        ),
        sa.Column("last_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_cve_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_cve")),
        sa.UniqueConstraint(
            "advisory_id", "cve_id", name=op.f("uq_advisory_cve_advisory_id_cve_id")
        ),
    )
    op.create_index(
        op.f("ix_advisory_cve_advisory_id"), "advisory_cve", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_cve_created_at"), "advisory_cve", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_advisory_cve_cve_id"), "advisory_cve", ["cve_id"], unique=False)
    op.create_index(
        op.f("ix_advisory_cve_enrichment_status"),
        "advisory_cve",
        ["enrichment_status"],
        unique=False,
    )
    op.create_table(
        "advisory_flag",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "REF_MISMATCH",
                "SEVERITY_MISMATCH",
                "NO_TEXT_LAYER",
                "UNKNOWN_SENDER",
                "LOW_TYPE_CONFIDENCE",
                "NO_CVE_FOUND",
                "POSSIBLE_REISSUE",
                "PDF_PARSE_FAILED",
                name="flagkind_enum",
            ),
            nullable=False,
        ),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_flag_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["user_account.id"],
            name=op.f("fk_advisory_flag_resolved_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_flag")),
    )
    op.create_index(
        op.f("ix_advisory_flag_advisory_id"), "advisory_flag", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_flag_created_at"), "advisory_flag", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_advisory_flag_kind"), "advisory_flag", ["kind"], unique=False)
    op.create_table(
        "advisory_ioc",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column(
            "ioc_type",
            sa.Enum(
                "IPV4",
                "IPV6",
                "DOMAIN",
                "URL",
                "MD5",
                "SHA1",
                "SHA256",
                "EMAIL",
                "FILENAME",
                "FILEPATH",
                "REGISTRY_KEY",
                "MUTEX",
                "USER_AGENT",
                "OTHER",
                name="ioctype_enum",
            ),
            nullable=False,
        ),
        sa.Column("ioc_type_raw", sa.String(length=120), nullable=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("defanged_value", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("first_seen_page", sa.Integer(), nullable=True),
        sa.Column("extraction_source", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_ioc_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_ioc")),
        sa.UniqueConstraint(
            "advisory_id",
            "ioc_type",
            "value",
            name=op.f("uq_advisory_ioc_advisory_id_ioc_type_value"),
        ),
    )
    op.create_index(
        op.f("ix_advisory_ioc_advisory_id"), "advisory_ioc", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_ioc_created_at"), "advisory_ioc", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_advisory_ioc_ioc_type"), "advisory_ioc", ["ioc_type"], unique=False)
    op.create_table(
        "advisory_product",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("product", sa.String(length=200), nullable=False),
        sa.Column("version_expression", sa.Text(), nullable=True),
        sa.Column("parsed_range", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fixed_version", sa.Text(), nullable=True),
        sa.Column(
            "source_of_claim",
            sa.Enum("NVD_CPE", "PDF_TEXT", "EMAIL_BODY", "MANUAL", name="claimsource_enum"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_product_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_product")),
    )
    op.create_index(
        op.f("ix_advisory_product_advisory_id"), "advisory_product", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_product_created_at"), "advisory_product", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_product_product"), "advisory_product", ["product"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_product_vendor"), "advisory_product", ["vendor"], unique=False
    )
    op.create_table(
        "advisory_ttp",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("THREAT_ACTOR", "MALWARE_FAMILY", "ATTACK_TECHNIQUE", name="ttpkind_enum"),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_advisory_ttp_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_ttp")),
        sa.UniqueConstraint(
            "advisory_id", "kind", "value", name=op.f("uq_advisory_ttp_advisory_id_kind_value")
        ),
    )
    op.create_index(
        op.f("ix_advisory_ttp_advisory_id"), "advisory_ttp", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_ttp_created_at"), "advisory_ttp", ["created_at"], unique=False
    )
    op.create_table(
        "comment",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_status_change", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(btrim(body)) > 0", name=op.f("ck_comment_body_not_blank")),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_comment_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user_account.id"],
            name=op.f("fk_comment_author_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
    )
    op.create_index(op.f("ix_comment_advisory_id"), "comment", ["advisory_id"], unique=False)
    op.create_index(op.f("ix_comment_created_at"), "comment", ["created_at"], unique=False)
    op.create_table(
        "related_advisory",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column("related_advisory_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "POSSIBLE_REISSUE",
                "SUPERSEDES",
                "SUPERSEDED_BY",
                "RELATES_TO",
                name="relationkind_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "detected_by",
            sa.Enum("TITLE_FINGERPRINT", "MANUAL", name="relationdetectedby_enum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "advisory_id <> related_advisory_id", name=op.f("ck_related_advisory_no_self_relation")
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_related_advisory_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["related_advisory_id"],
            ["advisory.id"],
            name=op.f("fk_related_advisory_related_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_related_advisory")),
        sa.UniqueConstraint(
            "advisory_id",
            "related_advisory_id",
            "kind",
            name=op.f("uq_related_advisory_advisory_id_related_advisory_id_kind"),
        ),
    )
    op.create_index(
        op.f("ix_related_advisory_advisory_id"), "related_advisory", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_related_advisory_created_at"), "related_advisory", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_related_advisory_related_advisory_id"),
        "related_advisory",
        ["related_advisory_id"],
        unique=False,
    )
    op.create_table(
        "status_change",
        sa.Column("advisory_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "ACKNOWLEDGED",
                "TRIAGED",
                "IN_PROGRESS",
                "AWAITING_VENDOR",
                "REMEDIATED",
                "RISK_ACCEPTED",
                "NOT_APPLICABLE",
                "CLOSED",
                name="advisorystatus_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "ACKNOWLEDGED",
                "TRIAGED",
                "IN_PROGRESS",
                "AWAITING_VENDOR",
                "REMEDIATED",
                "RISK_ACCEPTED",
                "NOT_APPLICABLE",
                "CLOSED",
                name="advisorystatus_enum",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("comment_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user_account.id"],
            name=op.f("fk_status_change_actor_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisory.id"],
            name=op.f("fk_status_change_advisory_id_advisory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.id"],
            name=op.f("fk_status_change_comment_id_comment"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_change")),
    )
    op.create_index(
        op.f("ix_status_change_advisory_id"), "status_change", ["advisory_id"], unique=False
    )
    op.create_index(
        op.f("ix_status_change_created_at"), "status_change", ["created_at"], unique=False
    )
    # ### end Alembic commands ###

    # ─── audit_log is append-only ────────────────────────────────────────────
    # Grants alone are insufficient: the application connects as the table
    # owner, and owners bypass table privileges. A trigger binds everyone.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log is append-only; % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_status_change_created_at"), table_name="status_change")
    op.drop_index(op.f("ix_status_change_advisory_id"), table_name="status_change")
    op.drop_table("status_change")
    op.drop_index(op.f("ix_related_advisory_related_advisory_id"), table_name="related_advisory")
    op.drop_index(op.f("ix_related_advisory_created_at"), table_name="related_advisory")
    op.drop_index(op.f("ix_related_advisory_advisory_id"), table_name="related_advisory")
    op.drop_table("related_advisory")
    op.drop_index(op.f("ix_comment_created_at"), table_name="comment")
    op.drop_index(op.f("ix_comment_advisory_id"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("ix_advisory_ttp_created_at"), table_name="advisory_ttp")
    op.drop_index(op.f("ix_advisory_ttp_advisory_id"), table_name="advisory_ttp")
    op.drop_table("advisory_ttp")
    op.drop_index(op.f("ix_advisory_product_vendor"), table_name="advisory_product")
    op.drop_index(op.f("ix_advisory_product_product"), table_name="advisory_product")
    op.drop_index(op.f("ix_advisory_product_created_at"), table_name="advisory_product")
    op.drop_index(op.f("ix_advisory_product_advisory_id"), table_name="advisory_product")
    op.drop_table("advisory_product")
    op.drop_index(op.f("ix_advisory_ioc_ioc_type"), table_name="advisory_ioc")
    op.drop_index(op.f("ix_advisory_ioc_created_at"), table_name="advisory_ioc")
    op.drop_index(op.f("ix_advisory_ioc_advisory_id"), table_name="advisory_ioc")
    op.drop_table("advisory_ioc")
    op.drop_index(op.f("ix_advisory_flag_kind"), table_name="advisory_flag")
    op.drop_index(op.f("ix_advisory_flag_created_at"), table_name="advisory_flag")
    op.drop_index(op.f("ix_advisory_flag_advisory_id"), table_name="advisory_flag")
    op.drop_table("advisory_flag")
    op.drop_index(op.f("ix_advisory_cve_enrichment_status"), table_name="advisory_cve")
    op.drop_index(op.f("ix_advisory_cve_cve_id"), table_name="advisory_cve")
    op.drop_index(op.f("ix_advisory_cve_created_at"), table_name="advisory_cve")
    op.drop_index(op.f("ix_advisory_cve_advisory_id"), table_name="advisory_cve")
    op.drop_table("advisory_cve")
    op.drop_index(op.f("ix_advisory_attachment_created_at"), table_name="advisory_attachment")
    op.drop_index(op.f("ix_advisory_attachment_advisory_id"), table_name="advisory_attachment")
    op.drop_table("advisory_attachment")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_expires_at"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_created_at"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_token_token_prefix"), table_name="api_token")
    op.drop_index(op.f("ix_api_token_created_at"), table_name="api_token")
    op.drop_table("api_token")
    op.drop_index(op.f("ix_advisory_title_fingerprint"), table_name="advisory")
    op.drop_index("ix_advisory_status_severity", table_name="advisory")
    op.drop_index(op.f("ix_advisory_status"), table_name="advisory")
    op.drop_index("ix_advisory_source_received", table_name="advisory")
    op.drop_index(op.f("ix_advisory_source_id"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_severity"), table_name="advisory")
    op.drop_index("ix_advisory_search_vector", table_name="advisory", postgresql_using="gin")
    op.drop_index(op.f("ix_advisory_resolution_due_at"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_received_at"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_priority"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_message_id"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_external_ref"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_dedupe_hash"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_created_at"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_acknowledged_at"), table_name="advisory")
    op.drop_index(op.f("ix_advisory_ack_due_at"), table_name="advisory")
    op.drop_table("advisory")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_created_at"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_source_created_at"), table_name="source")
    op.drop_table("source")
    op.drop_index("ix_cve_cpe_vendor_product", table_name="cve_cpe")
    op.drop_index(op.f("ix_cve_cpe_vendor"), table_name="cve_cpe")
    op.drop_index(op.f("ix_cve_cpe_product"), table_name="cve_cpe")
    op.drop_index(op.f("ix_cve_cpe_cve_id"), table_name="cve_cpe")
    op.drop_index(op.f("ix_cve_cpe_created_at"), table_name="cve_cpe")
    op.drop_table("cve_cpe")
    op.drop_index(op.f("ix_blob_sha256"), table_name="blob")
    op.drop_index(op.f("ix_blob_created_at"), table_name="blob")
    op.drop_table("blob")
    # ### end Alembic commands ###

    # ─── native enum types ───────────────────────────────────────────────────
    # op.drop_table() removes the columns that use these but leaves the
    # PostgreSQL ENUM types themselves behind — a known Alembic gap. Without
    # this, downgrade() then upgrade() collides on CREATE TYPE. Found by
    # actually running that cycle, not by inspection — see CLAUDE.md's Phase 2
    # progress-log entry.
    for enum_name in (
        "role_enum",
        "advisorytype_enum",
        "severity_enum",
        "priority_enum",
        "advisorystatus_enum",
        "ackchannel_enum",
        "flagkind_enum",
        "relationkind_enum",
        "relationdetectedby_enum",
        "extractionmethod_enum",
        "enrichmentstatus_enum",
        "ioctype_enum",
        "ttpkind_enum",
        "claimsource_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name};")
