"""add ioc remediation status

Revision ID: 65629d602d24
Revises: 2d99ec3309e7
Create Date: 2026-08-22 22:50:56.157749
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "65629d602d24"
down_revision: str | None = "2d99ec3309e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STATUS_ENUM = postgresql.ENUM(
    "DUE", "BLOCKED", "IN_PROGRESS", "RESOLVED", name="iocremediationstatus_enum"
)


def upgrade() -> None:
    # Unlike `create_table()`, `add_column()` does not implicitly `CREATE
    # TYPE` for a new enum — confirmed directly against the dev database
    # (autogenerate's plain `sa.Enum(...)` here raised `UndefinedObject:
    # type "iocremediationstatus_enum" does not exist`). Create the type
    # explicitly first, then reference it with `create_type=False` so the
    # column definition itself doesn't try to create it again.
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "advisory_ioc",
        sa.Column(
            "remediation_status",
            postgresql.ENUM(
                "DUE",
                "BLOCKED",
                "IN_PROGRESS",
                "RESOLVED",
                name="iocremediationstatus_enum",
                create_type=False,
            ),
            nullable=True,
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advisory_ioc", "remediation_status")
    # ### end Alembic commands ###
    # op.drop_column() does not drop the PostgreSQL native enum type this
    # column used — see D-023, a standing rule since Phase 2a.
    op.execute("DROP TYPE IF EXISTS iocremediationstatus_enum")
