"""add system_integration table

Revision ID: 67293c94f22d
Revises: cdd4c6b91707
Create Date: 2026-08-22 21:11:22.478249
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "67293c94f22d"
down_revision: str | None = "cdd4c6b91707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_integration",
        sa.Column(
            "kind", sa.Enum("NVD", "VIRUSTOTAL", name="systemintegrationkind_enum"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["integration_credential.id"],
            name=op.f("fk_system_integration_credential_id_integration_credential"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user_account.id"],
            name=op.f("fk_system_integration_updated_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_integration")),
        sa.UniqueConstraint("kind", name="uq_system_integration_kind"),
    )
    op.create_index(
        op.f("ix_system_integration_created_at"), "system_integration", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_integration_created_at"), table_name="system_integration")
    op.drop_table("system_integration")
    # ### end Alembic commands ###
    # op.drop_table() does not drop the PostgreSQL native enum type this
    # table's `kind` column used — see D-023, a standing rule since Phase 2a.
    op.execute("DROP TYPE IF EXISTS systemintegrationkind_enum")
