"""widen inventory vendor product columns

Revision ID: c4ccff4d5c82
Revises: 48a3c620953c
Create Date: 2026-08-22 12:48:19.127398
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4ccff4d5c82"
down_revision: str | None = "48a3c620953c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory_device_software",
        "vendor",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "inventory_device_software",
        "product",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_software",
        "vendor",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "inventory_software",
        "product",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "scan_match",
        "vendor",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "scan_match",
        "product",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "vendor_alias",
        "alias",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "vendor_alias",
        "canonical_vendor",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "vendor_alias",
        "canonical_product",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vendor_alias",
        "canonical_product",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "vendor_alias",
        "canonical_vendor",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "vendor_alias",
        "alias",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "scan_match",
        "product",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "scan_match",
        "vendor",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "inventory_software",
        "product",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_software",
        "vendor",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "inventory_device_software",
        "product",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_device_software",
        "vendor",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
