"""add vt_lookup table

Revision ID: cdd4c6b91707
Revises: c4ccff4d5c82
Create Date: 2026-08-22 20:34:17.910867
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cdd4c6b91707"
down_revision: str | None = "c4ccff4d5c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `ioctype_enum` and `enrichmentstatus_enum` already exist (created by
    # `advisory_ioc` and `advisory_cve` respectively in the initial
    # migration) — autogenerate doesn't detect cross-table enum reuse and
    # emits a plain `sa.Enum(..., create_type=False)`, which this SQLAlchemy
    # version does NOT actually honour inside `create_table()` (confirmed:
    # it still tried `CREATE TYPE` and collided). The dialect-specific
    # `postgresql.ENUM(..., create_type=False)` does correctly suppress it —
    # verified directly against the dev database before relying on it here.
    # See D-023/D-030.
    op.create_table(
        "vt_lookup",
        sa.Column(
            "ioc_type",
            postgresql.ENUM(
                "IPV4",
                "IPV6",
                "DOMAIN",
                "URL",
                "MD5",
                "SHA1",
                "SHA256",
                "EMAIL",
                "FILENAME",
                "FILEPATH",
                "REGISTRY_KEY",
                "MUTEX",
                "USER_AGENT",
                "OTHER",
                name="ioctype_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "OK",
                "NOT_FOUND",
                "ERROR",
                "SKIPPED_OFFLINE",
                name="enrichmentstatus_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by_id", sa.UUID(), nullable=True),
        sa.Column("malicious_count", sa.Integer(), nullable=True),
        sa.Column("suspicious_count", sa.Integer(), nullable=True),
        sa.Column("harmless_count", sa.Integer(), nullable=True),
        sa.Column("undetected_count", sa.Integer(), nullable=True),
        sa.Column("reputation", sa.Integer(), nullable=True),
        sa.Column("last_analysis_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permalink", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checked_by_id"],
            ["user_account.id"],
            name=op.f("fk_vt_lookup_checked_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vt_lookup")),
        sa.UniqueConstraint("ioc_type", "value", name="uq_vt_lookup_type_value"),
    )
    op.create_index(op.f("ix_vt_lookup_created_at"), "vt_lookup", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vt_lookup_created_at"), table_name="vt_lookup")
    op.drop_table("vt_lookup")
    # ### end Alembic commands ###
