"""widen cvss vector columns

Revision ID: f9d471469add
Revises: 4f03b42cc69d
Create Date: 2026-08-20 17:20:38.663323
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f9d471469add"
down_revision: str | None = "4f03b42cc69d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "advisory_cve",
        "cvss_v3_vector",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "advisory_cve",
        "cvss_v4_vector",
        existing_type=sa.VARCHAR(length=160),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "advisory_cve",
        "cvss_v4_vector",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=160),
        existing_nullable=True,
    )
    op.alter_column(
        "advisory_cve",
        "cvss_v3_vector",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=120),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
